apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  namespace: demo-saja
  labels:
    app: worker-pod
spec:
  containers:
    - name: worker-container
      image: saja123/worker-app:latest
      env: 
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: DB_HOST
          value: "postgresql-service"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "db"
        - name: DB_PORT
          value: "5432"
